### ISSUE TITLE
 send_nsca: consider adding --quiet option

### ISSUE THREAD

**Issue by sebastic** [NagiosEnterprises/nsca#12]
As reported by Timo Juhani Lindfors in [Debian Bug #605469](https://bugs.debian.org/605469)
> When I use send_nsca from cronjobs like
> ```
> #!/bin/sh
> set -e
> dumpdir=/data/mysqldump
> dumper="mysqldump --defaults-file=/etc/mysql/debian.cnf -h localhost -u debian-sys-maint"
> $dumper tau TauDatabase tau_measure > $dumpdir/tau.dump
> ...
> ...
> report="$(find $dumpdir/*.dump -printf "%f %s, ")"
> printf "data\tbackup-mysqldump\t0\t$report\n" | /usr/sbin/send_nsca -H nagios | grep -v "sent to host successfully."
> ```
> it is really annoying that I need to use the grep to suppress output that is printed when everything goes as requested.
> 
> Please consider the attached patch. It adds a --quiet option that does not print "sent to host successfully" if at least one result was sent.
> 
> (There is only long option since I figured plain "-q" might collide with something that upstream might add in the future.)

[send_nsca_document_quiet1.patch.txt](https://github.com/NagiosEnterprises/nsca/files/642695/send_nsca_document_quiet1.patch.txt)
[send_nsca_quiet_flag1.patch.txt](https://github.com/NagiosEnterprises/nsca/files/642696/send_nsca_quiet_flag1.patch.txt)

**Comment by jfrickson** [comment]
Sounds like a good idea. Looking into it.

**Comment by xavierba** [comment]
I made #38 out of this.

**Comment by xavierba** [comment]
#38 was merged so this bug report can be closed as fixed.

**Comment by sawolf** [comment]
Thanks for the reminder.
