### ISSUE TITLE
nsca can exit due to ECONNABORTED on FreeBSD

### ISSUE THREAD

**Issue by leres** [NagiosEnterprises/nsca#20]
We've had a lot of problems on our FreeBSD systems with the nsca daemon exiting due to ECONNABORTED. This is probably caused by cyber security scanning tickling a race condition in nsca itself.

The FreeBSD accept(2) man page says:

     [ECONNABORTED] A connection arrived, but it was closed while waiting on the listen queue.

<a href="https://gist.github.com/leres/3edbeaa1b1de3cf01e137f46d20f2743">Here is a minimal patch</a>. A better fix would be to never treat accept(2) errors as fatal.

**Comment by jfrickson** [comment]
Looking into it.

**Comment by ghost** [comment]
I may be hitting this at work as well. Patched locally, will see if this solves the unexpected NSCA daemon shutdowns.

**Comment by hedenface** [comment]
@feld What did you find? Did this solve your issue?

**Comment by ghost** [comment]
I can confirm this fixed the issue and is no longer crashing. We are shipping this patch with NSCA on FreeBSD

**Comment by xavierba** [comment]
@hedenface, the patch above looks like it has been tested, fixes the issue, and FreeBSD ships it for more than 2 years. This is likely valid for other platforms as well.
Can you please consider committing it ?

**Comment by xavierba** [comment]
I filed #39 with the patch rebased against maint branch.

**Comment by sawolf** [comment]
PR was merged - closing
