### ISSUE TITLE
Why is send_nsca doing an "escape_newline" ?

### ISSUE THREAD

**Issue by helorem** [NagiosEnterprises/nsca#23]
Using _send_nsca_, when the plugin_output contains a newline, the result is escaped.

Example : 
`printf "host\tservice\t0\tshort_description\nlong_description\n" | send_nsca -H shinken_host`

In this example, i expect `PLUGIN_OUTPUT="short_description"` and `LONG_PLUGIN_OUTPUT="long_description"`

Or, i get `PLUGIN_OUTPUT="short_description\\nlong_description"` and `LONG_PLUGIN_OUTPUT=""`

If I remove the line 254 of send_nsca.c `ptr4=escape_newlines(ptr4);`, the commad work as expected, so I wonder why is _send_nsca_ doing an _escape_newline_ ?

**Comment by hedenface** [comment]
Fixed in branch maint via commit 256abaf03ad0f5b892a697c8201438614f617c19
