### ISSUE TITLE
NSCA 2.9.2 does not accept updates from 2.7.2 clients

### ISSUE THREAD

**Issue by naterini** [NagiosEnterprises/nsca#27]
Updates sent to a 2.9.2 server get the following error from 2.7.2 clients:

Oct 09 14:00:06 node nsca[112032]: Handling the connection...
Oct 09 14:00:06 node nsca[112032]: Connection from x.x.x.x port 58017
Oct 09 14:00:06 node nsca[112032]: Time difference in packet: 0 seconds for host ysadmin1
Oct 09 14:00:06 node nsca[112032]: SERVICE CHECK -> Host Name: 'admin1', Service Description: 'df', Return Code: '0', Output: 'ok'
Oct 09 14:00:06 node nsca[112032]: Attempting to write to nagios command pipe
Oct 09 14:00:06 node nsca[112032]: End of connection...
Oct 09 14:00:06 node nsca[112032]: End of connection...
Oct 09 14:00:07 node nsca[112032]: Dropping packet with invalid CRC32 - possibly due to client using wrong password or crypto algorithm?
Oct 09 14:00:07 node nsca[112032]: End of connection...

**Comment by xavierba** [comment]
Both #19 and #33 should improve this. They allow to configure nsca client (send_nsca) to either use 2.7 or 2.9 packets. Both have been merged in maint branch and will be part of the hopefully close 2.9.3 release.
However, I believe what you are asking for is the nsca server to accept both 2.7 and 2.9 packets. This would indeed be a nice enhancement.

**Comment by xavierba** [comment]
Doesn't 3950d852b0289d38d0527bcd5076eaa00711d210 allow exactly that ? This commit is in 2.9.1.
I couldn't reproduce in a test setup.

**Comment by naterini** [comment]
Closing issue per response.
