### ISSUE TITLE
send_nsca incomplete output on timeout

### ISSUE THREAD

**Issue by millerh** [NagiosEnterprises/nsca#43]
$ send_nsca -H example.net
Error:

$ send_nsca --version
NSCA Client 2.10.0
Copyright (c) 2000-2007 Ethan Galstad (www.nagios.org)
Last Modified: 2020-04-15
License: GPL v2
Encryption Routines: AVAILABLE

Expected:
$ send_nsca -H example.net
Error: Timeout after 10 seconds

**Comment by sawolf** [comment]
Thanks for reporting this.

Should be fixed in master, but if the change doesn't work for some reason, let me know.
