### ISSUE TITLE
nsca-client 2.10.0 error return value 0 when '0 data packet(s) sent to host successfully.'

### ISSUE THREAD

**Issue by rdica** [NagiosEnterprises/nsca#45]
The CHANGELOG for 2.10 mentions "Send errors to stderr, where they belong (Bas Couwenberg / Sean Finney)".

In researching delimiter bug in nsca-client 2.10.0, I also found that the return value for unsuccessful sends is 0:

```
root@testhost:~# echo "localhost,0,Host UP at now"|/usr/sbin/send_nsca -H 192.168.15.28 -d ','
0 data packet(s) sent to host successfully.
root@testhost:~# echo ${PIPESTATUS[@]}
0 0
```
Is `0 data packet(s) sent to host successfully.` considered an error?

**Comment by christiancay** [comment]
@rdica I got the same situation too.

In this version 2.10.0, it's only sending packets when using defaults (using tabs and no specifying any delimiter with the -d option).

When trying delimiters the message received is: 
0 data packet(s) sent to host successfully.

**Comment by xavierba** [comment]
@christiancay `-d` option is broken in 2.10.0. See #44

**Comment by sawolf** [comment]
I agree that this is probably related to the issue with -d in the latest release. #44 should be fixed now, so if you still see this issue after compiling from `master`, let me know and we'll re-open this issue.

**Comment by xavierba** [comment]
@sawolf, I think this really is a different bug than #44.

If send_nsca is unable to send any packet to the nsca server, be it because of invalid (or supposedly invalid in the broken `-d` option case) input, the return code should not be 0.

**Comment by sawolf** [comment]
You're right - I was focused on the "not sending data packets" issue more than the return code.

edit: After thinking about it, I don't think the "0 packets sent" message is a bug. I suspect there are plenty of systems out there that may be intentionally running send_nsca on e.g. an empty file. I don't want to change the default behavior in that case, so I'm leaving this open as an enhancement request.

**Comment by xavierba** [comment]
@sawolf , I was not notified on the edit, so I've seen only your initial comment until now.

I'm curious , what would be the use case for sending empty and thus invalid payload ?

**Comment by sawolf** [comment]
For instance, you could be using passive checks to track events rather than scheduled checks (e.g. you want to send a check result when a service starts or stops, but don't care to relay the status on any defined interval). 
If check results are written to the file only when the necessary conditions trigger, but send_nsca is triggered on a regular interval (e.g. through cron), it would be 'normal' in this system to have 0 data packets sent, most of the time.

**Comment by macrotex** [comment]
Any idea when 2.10.1 with this fix will be released?
