### ISSUE TITLE
Containerizing nsca, requirement to run nsca in foreground

### ISSUE THREAD

**Issue by aakarshg** [NagiosEnterprises/nsca#48]
Hello, 

We're looking at containerizing nagios/nsca and run in a k8s environment, however i'm struggling to run nsca in foreground... it's just straight up exiting with a return code of 2 :( 

```
[root@nagios-production-9877455dd-xn6xz /]# nsca -c /usr/local/nagios/etc/nsca.cfg -f
[root@nagios-production-9877455dd-xn6xz /]# echo $?
2
```

I'm using the latest version of nsca.. does anyone have any suggestion on how i can get around this?

```
[root@nagios-production-9877455dd-xn6xz /]# nsca -h

NSCA - Nagios Service Check Acceptor
Copyright (c) 2009 Nagios Core Development Team and Community Contributors
Copyright (c) 2000-2009 Ethan Galstad
Version: 2.10.0
Last Modified: 2020-04-15
```

**Comment by xavierba** [comment]
Looks like this, at least, is not correct:
https://github.com/NagiosEnterprises/nsca/blob/9975fc7d4a694210d664cc9f78fc77152007e5f0/src/nsca.c#L207

This was introduced in:
https://github.com/NagiosEnterprises/nsca/commit/b7e76fe44e926b9cba9db0b466842826a459c1b9

**Comment by tuxgasy** [comment]
I try also to use nsca with Docker. It exited after call getaddrinfo function.
https://github.com/NagiosEnterprises/nsca/blob/9975fc7d4a694210d664cc9f78fc77152007e5f0/src/nsca.c#L844

In the config file nsca.cfg, `server_address` must be set (lik 0.0.0.0). And It works for me.
