### ISSUE TITLE
Provide option so nsca-client 2.9 works with existing nsca 2.7 servers

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nsca#9]
> This issue has been automatically migrated from http://tracker.nagios.org/view.php?id=0000356 - Please follow that link for details.
> Originally submitted on 2012-07-10 by stefanlasiewski

It appears that nsca-client 2.9 is not backwards compatible with the nsca 2.7.2 daemon due to a change in the size of the packet. See [1] and [2].

Many NSCA users are running nsca 2.7.2, because that is the latest stable version version available for RHEL, Fedora, Debian, etc. This means that we cannot use nsca-client 2.9 in an environment which has an existing NSCA environment, with 2.7.2. It will be difficult for us to upgrade our NSCA installations a step at a time.

Please add an option so that 2.9 client can send packets which are compatible with existing 2.7 servers. Perhaps an extra flag could be used to ensure that the packet size is compatible with nsca 2.7.2?

[1] http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670373
[2] http://support.nagios.com/forum/viewtopic.php?f=7&t=6401

**Comment by jfrickson** [comment]
We'll have to review this internally and make a decision.

**Comment by hedenface** [comment]
Just to chime in here: I personally am not a fan of maintaining backwards compatibility when it doesn't make sense. In this case maybe it is a gray area? Regardless, we will talk about it at the next open source internal dev meeting and reach a decision.

**Comment by hedenface** [comment]
Fixed via PR #19 via commit https://github.com/NagiosEnterprises/nsca/commit/3cb8d0ef0e307485814ae8d84716c34a41c3a0d8
